default:
	gofmt -s -w .
	# -t download packages for tasks and don't install after get (-d)
	go get -t -d ./...
	go install ./...
	@echo "built successfully"

validate:
	go test ./...
	golint -set_exit_status ./...
	go vet ./...

test:
	cd testdata && ./test.sh
