default:
	gofmt -s -w .
	go get -t -d ./...
	go install ./...
	@echo "built successfully"

check: default
	go get -x golang.org/x/lint/golint
	go test ./...
	golint -set_exit_status ./...
	go vet ./...
